In [2]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [3]:
fashion_mnist = keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

In [4]:
train_images.shape

(60000, 28, 28)

In [5]:
len(train_labels)

60000

In [6]:
np.unique(train_labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [7]:
test_images.shape

(10000, 28, 28)

In [8]:
len(test_labels)

10000

In [9]:
test_labels

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [10]:
train_images = train_images / 255.0

test_images = test_images / 255.0

In [11]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 128)               100480    
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [13]:
model.fit(train_images, train_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.4988 - accuracy: 0.8250
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3729 - accuracy: 0.8655
Epoch 3/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.3338 - accuracy: 0.8788
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3117 - accuracy: 0.8857
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2923 - accuracy: 0.8923


In [14]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

print('Test accuracy:', test_acc)

313/313 [==============================] - 1s 1ms/step - loss: 0.3477 - accuracy: 0.8771
Test accuracy: 0.8770999908447266


In [15]:
predictions = model.predict(test_images)

313/313 [==============================] - 1s 1ms/step


In [16]:
predictions[0]

array([4.7825858e-07, 2.1933570e-06, 1.0927889e-08, 4.6851440e-08,
       3.6188801e-08, 1.4386288e-03, 9.0970829e-08, 2.9726859e-02,
       7.7538396e-05, 9.6875417e-01], dtype=float32)

In [17]:
np.argmax(predictions[0])

9

In [18]:
test_labels[0]

9

In [19]:
img = test_images[0]

print(img.shape)

(28, 28)


In [20]:
img = (np.expand_dims(img,0))

print(img.shape)

(1, 28, 28)


In [21]:
predictions_single = model.predict(img)

print(predictions_single)

1/1 [==============================] - 0s 120ms/step
[[4.7825768e-07 2.1933570e-06 1.0927868e-08 4.6851440e-08 3.6188730e-08
  1.4386293e-03 9.0970829e-08 2.9726852e-02 7.7538396e-05 9.6875417e-01]]


In [22]:
np.argmax(predictions_single[0])

9